FirstProject/urls.py
from django.contrib import admin
from django.urls import path , include

#for import settings , static

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' ,include('apps.urls')),
    path('', include('usersauths.urls')), 
]

#Condition for  statics files 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)
    

apps/urls.py
from django.urls import path
from .import views
app_name = 'apps'

urlpatterns = [
    path('index/' , views.index , name = 'index'),
    path('category/' , views.category_list , name='category'),
    path('displayCategoryOfProducts/<int:productCategory_id>' , views.display_list_category_of_product , name='displayCategoryOfProducts'),
    path('vendor/' , views.vendor_list , name='vendor'),
    path('vendorDetail/<int:vendor_id>' , views.vendor_detail , name='vendorDetail'),
    path('productDetail/<int:product_id>' , views.product_detail , name='productDetail'),
]

apps/templates/apps/category_list.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}home{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="{% static 'apps/fichier/css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'apps/own/categories.css'%}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Sunflower:wght@300&display=swap" rel="stylesheet">
{% endblock styles %}
{% block content %}
<div class="category container bg-success rounded-3 mb-5">
    <h2 class="text-light">Category page </h2>
</div>
<div class="container d-flex align-items-center justify-content-sm-between mb-4">
    <div class="displayCount">
        <h2 class="text-black">{{categories.count}} Categories</h2>
    </div>
    <div class="input">
        <input type="text" name="text" id="text" placeholder="Search Categorie" class="form-control p-3">
    </div>
</div>
<div class="container-fluid w-100 d-flex align-items-center">
    <div class="partProducts ">
        <div class="container w-100">
            <div class="row">
                {% for category in categories %}
                <div class="col-md-4  ">
                    <div class="card shadow-sm mx-1 mb-3" style="width: 18rem;">
                        <div class="bagde position-absolute m-2  displayPourcentage  rounded-2 w-25 text-center py-1">
                            <i class="fa-regular fa-heart"></i>
                        </div>
                        <div class="hoverIcons d-flex  position-absolute justify-content-center">
                            <a href='{% url "apps:displayCategoryOfProducts" category.id %}' class="text-black text-decoration-none">
                                <i class="fa-regular fa-eye"></i>
                            </a>
                            <a href="#" class="text-black text-decoration-none"><i class="fa fa-share"></i></a>
                            <a href="#" class="text-black text-decoration-none">
                                <i class="fa-regular fa-heart"></i>
                            </a>
                        </div>
                        <a href='{% url "apps:displayCategoryOfProducts" category.id %}'>
                            <img src="{{category.image.url}}" class="card-img-top mx-auto p-3 rounded-2" alt="...">
                        </a>
                        <div class="card-body text-center">
                          <h5>{{category.title}}</h5>
                          <p>{{category.category.count}} Products identiques</p>
                        </div>
                      </div>
                </div>
                {% endfor %}
            </div>  
        </div>
    </div>
    <div class="partCategory w-25  p-4 ">
        <div class="boxPartCategory border-1 rounded-2 w-100 shadow-lg h-100 p-0">
            <h2 class="p-3 borderBottomm">  Filter by price</h2>
            <div class="d-flex justify-content-between p-2">
                <h6 class="text-success">From $500</h6>  
                <h6 class="text-success"> To $1000</h6>
            </div>
            <div class="container">
                <p>Color</p>
                <div class="d-flex flex-column">
                    <div class="d-flex mb-3 ">
                        <input type="checkbox" name="red" id="" value="Red"> <span class="px-2">Red (45)</span>
                    </div>
                    <div class="d-flex mb-3">
                        <input type="checkbox" name="blue" id="blue" value="blue"> <span class="px-2">Blue (95)</span>
                    </div>
                    <div class="d-flex mb-4 ">
                        <input type="checkbox" name="green" id="green" value="green"> <span class="px-2">Green (25)</span>
                    </div>
                </div>
            </div>
            <div class="container mb-3">
                <p>Item Condition</p>
                <div class="d-flex flex-column">
                    <div class="d-flex mb-3 ">
                        <input type="checkbox" name="red" id="" value="Red"> <span class="px-2">New (45)</span>
                    </div>
                    <div class="d-flex mb-3">
                        <input type="checkbox" name="blue" id="blue" value="blue"> <span class="px-2">Used (95)</span>
                    </div>
                    <div class="d-flex ">
                        <input type="checkbox" name="green" id="green" value="green"> <span class="px-2">Refurshied (25)</span>
                    </div>
                </div>
            </div>
          <div class="d-flex align-items-center justify-content-lg-around ">
            <button class="btn btn-success text-light">
                <i class="fa fa-filter"></i> Filter
            </button>
            <img src="{% static "apps/asset/image/th.jpg" %}" class='w-50 h-50' alt="">
          </div>
          
        </div>
        <div class="boxPartCategory border-1 rounded-2 w-100 shadow-lg h-100 p-0 ">
            <h2 class="p-3 borderBottomm mt-5 mb-3">Category</h2>

            <div class="d-flex  flex-column ">
                 {% for cat in categories   %}
            <div class="d-flex  flex-column ">
                <div class="d-flex align-items-center justify-content-between mb-4 ">
                    <a href="{% url "apps:displayCategoryOfProducts" cat.id %}" class="px-2 mx-5 mb-2 text-decoration-none text-black h5 displayBorderCategory">
                       {{cat.title}}
                    </a>
                </div>
            </div>    
            {% endfor %}
            </div>
           
          
        </div>
        <div class=" container boxPartCategory border-1 rounded-2 w-100 shadow-lg h-7 p-0 ">
            <h2 class="p-3 borderBottomm mt-5 mb-3">New Products</h2>
            {% for prod in product  %}
            <div class="d-flex  flex-column w-100 ">
                <div class="d-flex align-items-center mb-4 justify-content-evenly ">
                    <div class="imageNewProducts w-50">
                        <img src="{{prod.image.url}}" class="rounded-2 w-75 h-75 mx-2" alt="">
                    </div>
                    <div class="d-flex flex-column w-50">
                        <div class="title">
                            <h4 class="text-success">{{prod.title}}</h4>
                        </div>
                        <div class="price">
                            <h6>{{prod.price}}</h6>
                        </div>
                        <div class="star">
                            <h6>⭐⭐</h6>
                        </div>
                    </div>
                </div>
               
            </div>        
            {% endfor %}
      
           
          
        </div>
    </div>
</div>

<script src="{% static 'apps/fichier/js/bootstrap.bundle.min.js' %}"></script>
{% endblock content %}

apps/templates/apps/displayCategoryOfProduct.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}home{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="{% static 'apps/fichier/css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'apps/own/displayCategoryOfProduct.css'%}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Sunflower:wght@300&display=swap" rel="stylesheet">
{% endblock styles %}
{% block content %}
<div class="category container bg-success rounded-3 mb-5">
    <h2 class="text-light">{{category.title}}</h2>
</div>

<div class="container d-flex align-items-center justify-content-sm-between mb-4">
    <div class="displayCount">
        <h2 class="text-black">{{products.count}} Product(s)</h2>
    </div>
    <div class="input">
        <input type="text" name="text" id="text" placeholder="Search Categorie" class="form-control p-3">
    </div>
</div>
<div class="container-fluid w-100">
    <div class="partProducts w-100 ">
        <div class="container w-100">
            <div class="row mt-5">
                {% if products_count == 0 %}
                    <div class="container-fluid text-center text-black">
                        <h3>Oups no products for this category...</h3>
                    </div>
                {% else %}
                {% for category in products %}
                <div class="col-md-3">
                    <div class="card shadow-sm mx-1 mb-3" style="width: 18rem;">
                        <div class="bagde position-absolute m-2 bg-success text-light displayPourcentage  rounded-2 w-25 text-center py-1">
                            <i class="fa fa-heart"></i>
                        </div>
                        <div class="hoverIcons d-flex  position-absolute justify-content-center">
                            <a href='{% url "apps:displayCategoryOfProducts" category.id %}' class="text-black text-decoration-none">
                                <i class="fa fa-eye"></i>
                            </a>
                            <a href="#" class="text-black text-decoration-none"><i class="fa-regular fa-share"></i></a>
                            <a href="#" class="text-black text-decoration-none">
                                <i class="fa fa-heart"></i>
                            </a>
                        </div>
                        <a href="{% url "apps:displayCategoryOfProducts" category.id %}">
                            <img src="{{category.image.url}}" class="card-img-top mx-auto p-3 rounded-2" alt="...">
                        </a>
                        <div class="card-body text-center">
                          <h5>{{category.title}}</h5>
                          <p>{{category.category.count}} Products identiques</p>
                        </div>
                      </div>
                </div>
                {% endfor %}
                {% endif %}
            </div>  
        </div>
    </div>
</div>
<script src="{% static 'apps/fichier/js/bootstrap.bundle.min.js' %}"></script>
{% endblock content %}

apps/templates/apps/index.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}home{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="{% static 'apps/fichier/css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'apps/own/styles.css'%}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Sunflower:wght@300&display=swap" rel="stylesheet">
{% endblock styles %}
{% block content %}
   <div class="container-fluid w-100 d-flex align-items-center">
        <div class="partCategory w-25  p-4 ">
            <div class="boxPartCategory border-1 rounded-2 w-100 shadow-lg h-100 p-0">
                <h2 class="p-3 borderBottomm">  Filter by price</h2>
                <div class="d-flex justify-content-between p-2">
                    <h6 class="text-success">From $500</h6>  
                    <h6 class="text-success"> To $1000</h6>
                </div>
                <div class="container">
                    <p>Color</p>
                    <div class="d-flex flex-column">
                        <div class="d-flex mb-3 ">
                            <input type="checkbox" name="red" id="" value="Red"> <span class="px-2">Red (45)</span>
                        </div>
                        <div class="d-flex mb-3">
                            <input type="checkbox" name="blue" id="blue" value="blue"> <span class="px-2">Blue (95)</span>
                        </div>
                        <div class="d-flex mb-4 ">
                            <input type="checkbox" name="green" id="green" value="green"> <span class="px-2">Green (25)</span>
                        </div>
                    </div>
                </div>
                <div class="container mb-3">
                    <p>Item Condition</p>
                    <div class="d-flex flex-column">
                        <div class="d-flex mb-3 ">
                            <input type="checkbox" name="red" id="" value="Red"> <span class="px-2">New (45)</span>
                        </div>
                        <div class="d-flex mb-3">
                            <input type="checkbox" name="blue" id="blue" value="blue"> <span class="px-2">Used (95)</span>
                        </div>
                        <div class="d-flex ">
                            <input type="checkbox" name="green" id="green" value="green"> <span class="px-2">Refurshied (25)</span>
                        </div>
                    </div>
                </div>
              <div class="d-flex align-items-center justify-content-lg-around ">
                <button class="btn btn-success text-light">
                    <i class="fa fa-filter"></i> Filter
                </button>
                <img src="{% static "apps/asset/image/th.jpg" %}" class='w-50 h-50' alt="">
              </div>
              
            </div>
            <div class="boxPartCategory border-1 rounded-2 w-100 shadow-lg h-100 p-0 ">
                <h2 class="p-3 borderBottomm mt-5 mb-3">Category</h2>
                {% for c in category %}
                <div class="d-flex  flex-column ">
                    <div class="d-flex align-items-center justify-content-between mb-4 displayBorderCategory ">
                        <a href="{% url "apps:displayCategoryOfProducts" c.id %}" class="px-2 mx-0 mb-2 text-decoration-none text-black h5 ">
                            {{c.title}} 
                        </a>
                        <span class="displayNumberCategoryDisponible">{{c.category.count}}</span>
                    </div>
                </div>
                {% endfor %}
              
               
              
            </div>
            <div class=" container boxPartCategory border-1 rounded-2 w-100 shadow-lg h-7 p-0 ">
                <h2 class="p-3 borderBottomm mt-5 mb-3">New Products</h2>
                {% for prod in product %}
                <div class="d-flex  flex-column w-100 ">
                    <div class="d-flex align-items-center mb-4 justify-content-evenly ">
                        <div class="imageNewProducts w-50">
                            <img src="{{prod.image.url}}" class="rounded-2 w-75 h-75 mx-2" alt="">
                        </div>
                        <div class="d-flex flex-column w-50">
                            <div class="title">
                                <h4 class="text-success">
                                    <a href="{% url "apps:productDetail" prod.id %}" class="text-decoration-none text-black">
                                        {{prod.title}}
                                    </a>
                                </h4>
                            </div>
                            <div class="price">
                                <h6>${{prod.price}}</h6>
                            </div>
                            <div class="star">
                                <h6>⭐⭐</h6>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
             
               
              
            </div>
        </div>
        
        <div class="partProducts ">
            <div class="box1 w-100 rounded-1 mx-auto position-relative ">
                <img  src="{% static 'apps/asset/image/OIP.jpg' %}" class="rounded-2" alt="">
                <div class="col-md-6 mx-2 position-absolute welcome mb-3">
                    <div class="container">
                        <h1 class="text-black">Don't miss amazing <br> grocery deals </h1>
                        <h4 class="text-light">Sign up for the newlestter</h4>
                        <div class="d-flex">
                            <input type="text" placeholder="  Your email adress" class="form-control mx-1 p-3 rounded-4">
                            <button class="btn btn-success rounded-4">Susbcribe</button>
                        </div>
                    </div>
                  
                </div>
                <div class="col-md-6"></div>
            </div>
            <div class="d-flex aling-items-center justify-content-between mt-3 mb-2 mx-1">
                <h2 >Popular Products</h2>
                <div class="element">
                    <a href="{% url "apps:index" %}" class='active'>All Product</a>
                    <a href="#">Milk & Diaries</a>
                    <a href="#">Coffe & Teas </a>
                    <a href="#">Peats Food</a>
                    <a href="#">Meat</a>
                    <a href="#">Vegeetable</a>
                    <a href="#">Fruits</a>
                </div>
            </div>
            <div class="container w-100">
                <div class="row">
                    {% for p in products %}
                    <div class="col-md-4  ">
                        
                        <div class="card shadow-sm mx-1 mb-3" style="width: 18rem;">
                            <div class="bagde position-absolute m-2 displayPourcentage bg-danger rounded-2 w-25 text-center py-1">
                                <p class="text-light ">-{{p.get_pourcentage|floatformat:0}}%</p>
                            </div>
                            <div class="hoverIcons d-flex  position-absolute justify-content-center">
                                <a href="{% url 'apps:productDetail' p.id %}" class="text-black text-decoration-none">
                                    <i class="fa-regular fa-eye"></i>
                                </a>
                                <a href="#" class="text-black text-decoration-none"><i class="fa fa-share"></i></a>
                                <a href="#" class="text-black text-decoration-none">
                                    <i class="fa-regular fa-heart"></i> 
                                </a>
                                
                                
                            </div>
                            <a href='{% url "apps:productDetail" p.id %}'>
                                <img src="{{p.image.url}}" class="card-img-top mx-auto p-3 rounded-2" alt="...">
                            </a>
                            
                            <div class="card-body">
                              <p class="card-text">{{p.category.title}}</p>
                              <h5>{{p.title}}</h5>
                              <p>⭐⭐⭐⭐</p>
                              <div class="d-flex justify-content-between align-items-center">
                                <div class="price">
                                   $ {{p.price}}
                                </div>
                                <div class="old-price">
                                    <strike>
                                        $ {{p.old_price}}
                                    </strike>
                                </div>
                                <div class="cart">
                                    <button class="btn btn-info rounded-1 p-1 text-light"><i class="fa fa-shopping-cart"></i> Add</button>
                                </div>
                              </div>
                            </div>
                          </div>
                    </div>
                    {% endfor %}
                   
                </div>
                
                
            </div>
        </div>
   </div>
    <script src="{% static 'apps/fichier/js/bootstrap.bundle.min.js' %}"></script>
{% endblock content %}

apps/templates/apps/listVendors.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}Vendor{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="{% static 'apps/fichier/css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'apps/own/listVendors.css'%}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Sunflower:wght@300&display=swap" rel="stylesheet">
{% endblock styles %}
{% block content %}
<div class="container text-center mt-5  justify-content-center aling-items-center w-100">
    <h1 class="mb-3">Vendors List: <span >
        {{vendors_count}}
    </span> </h1>
        <form action="" class="position-relative ">
            <input type="text" name="vendor" id="vendo" placeholder="Search your vendors" class="rounded-4 p-3 
            form-control shadow-lg">
            <button type="submit" class="border-0 position-absolute"><i class="fa fa-search"></i></button>
        </form>
</div>

<div class="container-fluid mt-4 mx-5 p-1 w-100 justify-content-center">
    <div class="row p-3 m-3">
        
        {% for v in vendor  %}
        <div class="col-md-4  imagesBorder mx-5 mb-5">
            <div class="d-flex align-items-center ">
                <div class="container d-flex flex-column image  ">
                    <a href="{% url 'apps:vendorDetail' v.id %}">
                        <img src="{{v.image.url}}" class="mx-4" alt="">
                    </a>
                    <div class="container mt-3">
                        <p class="mx-4 btn btn-success border-success p-2">
                            <a class="text-light text-decoration-none" data-bs-target="#seeeModalToggle" data-bs-toggle="modal">
                                {{v.vendor.all.count}} Products
                            </a>
                        </p>
                    </div>
                </div>
                <div class="container">
                    <a href="{% url 'apps:vendorDetail' v.id %}" class="text-success h2 text-decoration-none">
                        {{v.title}}</a> <span>⭐⭐⭐⭐⭐</span>
                    <p>Since {{v.date|date:'Y'}} </p>
                    <p> <i class="fa fa-map-marker-alt"></i> {{v.address}}</p>
                    <p>Call us:{{v.contact}}</p>
                    
                </div>
              
            </div>
        </div>
        {% endfor %}
    
    </div>

</div>
<div class="modal fade" id="seeeModalToggle" aria-hidden="true" aria-labelledby="seeeModalToggleLabel" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header text-center">
              <h1 class="modal-title fs-5" id="seeeModalToggle">Notifications</h1>
              
              <button type="button" class="btn-close mx-1" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            
            <div class="modal-body text-start">
                <p class="text-danger">Impossible to display all products here ! i'm sorry</p>
             </div>      
            
           
          </div>
        </div>
      </div>
<script src="{% static 'apps/fichier/js/bootstrap.bundle.min.js' %}"></script>
{% endblock content %}

apps/templates/apps/vendorDetail.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}Vendor{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="{% static 'apps/fichier/css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'apps/own/vendorsDetail.css'%}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Sunflower:wght@300&display=swap" rel="stylesheet">
{% endblock styles %}

{% block content %}
<div class="container rounded-2  shadow-lg border-1 border-light mt-5  p-4">
    <div class="container-fluid d-flex aling-items-center">
        <div class="boxOneImage">
            <img src="{{ vendor.image.url }}" alt="">
        </div>
        <div class="boxOneTitle mt-1 mx-3 text-center">
            <p> Since {{vendor.date|date:'Y'}}</p>
            <h1>{{vendor.title}}</h1>
            <p>⭐⭐⭐⭐⭐ (5)</p>
            <p>{{vendor.description}}</p>
        </div>
    </div>
</div>
<div class="container-fluid w-100 d-flex align-items-center">
    <div class="partCategory w-25  p-4 mt-5 ">
        <div class="boxPartCategory border-1 rounded-2 w-100 shadow-lg h-100 p-0">
            <h2 class="p-3 borderBottomm">  Filter by price</h2>
            <div class="d-flex justify-content-between p-2">
                <h6 class="text-success">From $500</h6>  
                <h6 class="text-success"> To $1000</h6>
            </div>
            <div class="container">
                <p>Color</p>
                <div class="d-flex flex-column">
                    <div class="d-flex mb-3 ">
                        <input type="checkbox" name="red" id="" value="Red"> <span class="px-2">Red (45)</span>
                    </div>
                    <div class="d-flex mb-3">
                        <input type="checkbox" name="blue" id="blue" value="blue"> <span class="px-2">Blue (95)</span>
                    </div>
                    <div class="d-flex mb-4 ">
                        <input type="checkbox" name="green" id="green" value="green"> <span class="px-2">Green (25)</span>
                    </div>
                </div>
            </div>
            <div class="container mb-3">
                <p>Item Condition</p>
                <div class="d-flex flex-column">
                    <div class="d-flex mb-3 ">
                        <input type="checkbox" name="red" id="" value="Red"> <span class="px-2">New (45)</span>
                    </div>
                    <div class="d-flex mb-3">
                        <input type="checkbox" name="blue" id="blue" value="blue"> <span class="px-2">Used (95)</span>
                    </div>
                    <div class="d-flex ">
                        <input type="checkbox" name="green" id="green" value="green"> <span class="px-2">Refurshied (25)</span>
                    </div>
                </div>
            </div>
          <div class="d-flex align-items-center justify-content-lg-around ">
            <button class="btn btn-success text-light">
                <i class="fa fa-filter"></i> Filter
            </button>
            <img src="{% static "apps/asset/image/th.jpg" %}" class='w-50 h-50' alt="">
          </div>
          
        </div>
        <div class="boxPartCategory border-1 rounded-2 w-100 shadow-lg h-100 p-0 ">
            <h2 class="p-3 borderBottomm mt-5 mb-3">Category</h2>
            {% for cat in category   %}
            <div class="d-flex  flex-column ">
                <div class="d-flex align-items-center justify-content-between mb-4 ">
                    <a href="{% url "apps:displayCategoryOfProducts" cat.id %}" class="px-2 mx-5 mb-2 text-decoration-none text-black h5 displayBorderCategory">
                       {{cat.title}}
                    </a>
                </div>
            </div>    
            {% endfor %}
          
           
          
        </div>
        <div class=" container boxPartCategory border-1 rounded-2 w-100 shadow-lg h-7 p-0 ">
            <h2 class="p-3 borderBottomm mt-5 mb-3">New Products</h2>
            {% for prod in product  %}
            <div class="d-flex  flex-column w-100 ">
                <div class="d-flex align-items-center mb-4 justify-content-evenly ">
                    <div class="imageNewProducts w-50">
                        <img src="{{prod.image.url}}" class="rounded-2 w-75 h-75 mx-2" alt="">
                    </div>
                    <div class="d-flex flex-column w-50">
                        <div class="title">
                            <h4 class="text-success">{{prod.title}}</h4>
                        </div>
                        <div class="price">
                            <h6>{{prod.price}}</h6>
                        </div>
                        <div class="star">
                            <h6>⭐⭐</h6>
                        </div>
                    </div>
                </div>
               
            </div>        
            {% endfor %}
      
           
          
        </div>
    </div>
    <div class="partProducts">
        <div class="title mb-5">
            <h4 class="text-success">We have {{products.all.count}} products for you!</h4>
        </div>
        {% for p in products  %}
        <div class="container-fluid d-flex align-items-center">
            <div class="imageBorder m-4 ">
                <img src="{{p.image.url}}" class="img mb-3 p-2" alt="">
            </div>
            <div class="informationOnProducts mx-2">
                <p>{{p.get_pourcentage|floatformat:0}}</p>
                <h4>{{p.title}}</h4>
                <p>⭐⭐⭐⭐⭐(5.0)</p>
                <p>{{p.description}}</p>
                <h4 class="text-success">${{p.price}}</h4>
                <button class="btn btn-success btn-lg">
                    <i class="fa fa-shopping-cart"></i> Add Card
                </button>
            </div>
        </div>
        {% endfor %}
       
    </div>
</div>
<script src="{% static 'apps/fichier/js/bootstrap.bundle.min.js' %}"></script>  
{% endblock content %}